rly_file = "Xmas2021.rly"
ttb_files = [ "Xmas2021.ttb",]
ssn_files = [ "Xmas2021.ssn",]
country_code = "FN"
name = "Christmas 2021 Celebratory Route"
description = "A fictional christmas inspired route with no requirement for service punctuality, just for entertainment"
display_name = "Xmas2021"
author = "ROSDev Team"
contributors = [ "Krizar",]
